var json = {
    "match1": {
        "gDate": ["Game Date: ", "2012-10-27"],
        "gTime": ["Game Time: ", "08:00"],
        "gField": ["Game Field: ", "1B"],
        "gAge": ["Age Group: ", "U12"],
        "gGender": ["Gender: ", "Boys"],
        "gComp": ["Is Competitive: ", "true"],
        "gHome": ["Home Team: ", "LFC"],
        "gAway": ["Away Team: ", "TBU"],
        "gComments": ["Comments: ", "None"],
        "ref": ["Referee: ", "Adam Crawford"],
        "refGrd": ["Grade: ", "8"],
        "refYrs": ["Years Reffing: ", "10"],
        "refEml": ["E-Mail: ", "geeksbsmrt@gmail.com"],
        "ar1": ["AR 1: ", "Matthew Crawford"],
        "ar1Grd": ["Grade: ", "8"],
        "ar1Yrs": ["Years Reffing: ", "10"],
        "ar1Eml": ["E-Mail: ", "test@test.com"],
        "ar2": ["AR 2: ", "Bill Crawford"],
        "ar2Grd": ["Grade: ", "8"],
        "ar2Yrs": ["Years Reffing: ", "10"],
        "ar2Eml": ["E-Mail: ", "billcrawford@polk-county.net"]
    },
    "match2": {
        "gDate": ["Game Date: ", "2012-10-27"],
        "gTime": ["Game Time: ", "09:30"],
        "gField": ["Game Field: ", "2"],
        "gAge": ["Age Group: ", "U18"],
        "gGender": ["Gender: ", "Girls"],
        "gComp": ["Is Competitive: ", "false"],
        "gHome": ["Home Team: ", "North Lakeland"],
        "gAway": ["Away Team: ", "Lake Wales"],
        "gComments": ["Comments: ", "None"],
        "ref": ["Referee: ", "Bill Crawford"],
        "refGrd": ["Grade: ", "8"],
        "refYrs": ["Years Reffing: ", "10"],
        "refEml": ["E-Mail: ", "billcrawford@polk-county.net"],
        "ar1": ["AR 1: ", "Adam Crawford"],
        "ar1Grd": ["Grade: ", "8"],
        "ar1Yrs": ["Years Reffing: ", "10"],
        "ar1Eml": ["E-Mail: ", "geeksbsmrt@gmail.com"],
        "ar2": ["AR 2: ", "Matthew Crawford"],
        "ar2Grd": ["Grade: ", "8"],
        "ar2Yrs": ["Years Reffing: ", "10"],
        "ar2Eml": ["E-Mail: ", "test@test.com"]
    },
    "match3": {
        "gDate": ["Game Date: ", "2012-10-27"],
        "gTime": ["Game Time: ", "11:00"],
        "gField": ["Game Field: ", "2"],
        "gAge": ["Age Group: ", "U16"],
        "gGender": ["Gender: ", "Boys"],
        "gComp": ["Is Competitive: ", "true"],
        "gHome": ["Home Team: ", "LFC"],
        "gAway": ["Away Team: ", "TBU"],
        "gComments": ["Comments: ", "None"],
        "ref": ["Referee: ", "Adam Crawford"],
        "refGrd": ["Grade: ", "8"],
        "refYrs": ["Years Reffing: ", "10"],
        "refEml": ["E-Mail: ", "geeksbsmrt@gmail.com"],
        "ar1": ["AR 1: ", "Matthew Crawford"],
        "ar1Grd": ["Grade: ", "8"],
        "ar1Yrs": ["Years Reffing: ", "10"],
        "ar1Eml": ["E-Mail: ", "test@test.com"],
        "ar2": ["AR 2: ", "Bill Crawford"],
        "ar2Grd": ["Grade: ", "8"],
        "ar2Yrs": ["Years Reffing: ", "10"],
        "ar2Eml": ["E-Mail: ", "billcrawford@polk-county.net"]
    },
    "match4": {
        "gDate": ["Game Date: ", "2012-10-27"],
        "gTime": ["Game Time: ", "13:00"],
        "gField": ["Game Field: ", "2"],
        "gAge": ["Age Group: ", "U18"],
        "gGender": ["Gender: ", "Girls"],
        "gComp": ["Is Competitive: ", "false"],
        "gHome": ["Home Team: ", "North Lakeland"],
        "gAway": ["Away Team: ", "Haines City"],
        "gComments": ["Comments: ", "None"],
        "ref": ["Referee: ", "Matthew Crawford"],
        "refGrd": ["Grade: ", "8"],
        "refYrs": ["Years Reffing: ", "10"],
        "refEml": ["E-Mail: ", "test@test.com"],
        "ar1": ["AR 1: ", "Adam Crawford"],
        "ar1Grd": ["Grade: ", "8"],
        "ar1Yrs": ["Years Reffing: ", "10"],
        "ar1Eml": ["E-Mail: ", "geeksbsmrt@gmail.com"],
        "ar2": ["AR 2: ", "Bill Crawford"],
        "ar2Grd": ["Grade: ", "8"],
        "ar2Yrs": ["Years Reffing: ", "10"],
        "ar2Eml": ["E-Mail: ", "billcrawford@polk-county.net"]
    }
};